Controllers/HomeController.cs
using ClimeiMvc.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ClimeiMvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly climei_mvcContext _context;

        public HomeController(climei_mvcContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var Users = _context.Usuario.Count();
            var NiveisUmidade = _context.NivelUmidade.Count();
            var NiveisTemperatura = _context.NivelTemperatura.Count();

            ViewData["QntdUsers"] = Users;
            ViewData["QntdUmidade"] = NiveisUmidade;
            ViewData["QntdTemp"] = NiveisTemperatura;
                
            return View();
        }
    }
}

Controllers/NivelTemperaturasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ClimeiMvc.Data;
using ClimeiMvc.Models;

namespace ClimeiMvc.Controllers
{
    public class NivelTemperaturasController : Controller
    {
        private readonly climei_mvcContext _context;

        public NivelTemperaturasController(climei_mvcContext context)
        {
            _context = context;
        }

        // GET: NivelTemperaturas
        public async Task<IActionResult> Index(string message)
        {
            ViewBag.Message = message;

            return _context.NivelTemperatura != null ? 
                          View(await _context.NivelTemperatura.ToListAsync()) :
                          Problem("Entity set 'climei_mvcContext.NivelTemperatura'  is null.");
        }

        // GET: NivelTemperaturas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.NivelTemperatura == null)
            {
                return NotFound();
            }

            var nivelTemperatura = await _context.NivelTemperatura
                .FirstOrDefaultAsync(m => m.Id == id);
            if (nivelTemperatura == null)
            {
                return NotFound();
            }

            return View(nivelTemperatura);
        }

        // GET: NivelTemperaturas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: NivelTemperaturas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Faixa,DateAvaliacao")] NivelTemperatura nivelTemperatura)
        {
            if (ModelState.IsValid)
            {
                _context.Add(nivelTemperatura);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { message = "Registro criado com sucesso" });
            }
            return View(nivelTemperatura);
        }

        // GET: NivelTemperaturas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.NivelTemperatura == null)
            {
                return NotFound();
            }

            var nivelTemperatura = await _context.NivelTemperatura.FindAsync(id);
            if (nivelTemperatura == null)
            {
                return NotFound();
            }
            return View(nivelTemperatura);
        }

        // POST: NivelTemperaturas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Faixa,DateAvaliacao")] NivelTemperatura nivelTemperatura)
        {
            if (id != nivelTemperatura.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(nivelTemperatura);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NivelTemperaturaExists(nivelTemperatura.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { message = "Registro atualizado com sucesso" });
            }
            return View(nivelTemperatura);
        }

        // GET: NivelTemperaturas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.NivelTemperatura == null)
            {
                return NotFound();
            }

            var nivelTemperatura = await _context.NivelTemperatura
                .FirstOrDefaultAsync(m => m.Id == id);
            if (nivelTemperatura == null)
            {
                return NotFound();
            }

            return View(nivelTemperatura);
        }

        // POST: NivelTemperaturas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.NivelTemperatura == null)
            {
                return Problem("Entity set 'climei_mvcContext.NivelTemperatura'  is null.");
            }
            var nivelTemperatura = await _context.NivelTemperatura.FindAsync(id);
            if (nivelTemperatura != null)
            {
                _context.NivelTemperatura.Remove(nivelTemperatura);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { message = "Registro removido com sucesso" });
        }

        private bool NivelTemperaturaExists(int id)
        {
          return (_context.NivelTemperatura?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/NivelUmidadesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ClimeiMvc.Data;
using ClimeiMvc.Models;

namespace ClimeiMvc.Controllers
{
    public class NivelUmidadesController : Controller
    {
        private readonly climei_mvcContext _context;

        public NivelUmidadesController(climei_mvcContext context)
        {
            _context = context;
        }

        // GET: NivelUmidades
        public async Task<IActionResult> Index(string message)
        {
            ViewBag.Message = message;

            return _context.NivelUmidade != null ? 
                          View(await _context.NivelUmidade.ToListAsync()) :
                          Problem("Entity set 'climei_mvcContext.NivelUmidade'  is null.");
        }

        // GET: NivelUmidades/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.NivelUmidade == null)
            {
                return NotFound();
            }

            var nivelUmidade = await _context.NivelUmidade
                .FirstOrDefaultAsync(m => m.Id == id);
            if (nivelUmidade == null)
            {
                return NotFound();
            }

            return View(nivelUmidade);
        }

        // GET: NivelUmidades/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: NivelUmidades/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Faixa,DateAvaliacao")] NivelUmidade nivelUmidade)
        {
            if (ModelState.IsValid)
            {
                _context.Add(nivelUmidade);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { message = "Registro criado com sucesso" });
            }
            return View(nivelUmidade);
        }

        // GET: NivelUmidades/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.NivelUmidade == null)
            {
                return NotFound();
            }

            var nivelUmidade = await _context.NivelUmidade.FindAsync(id);
            if (nivelUmidade == null)
            {
                return NotFound();
            }
            return View(nivelUmidade);
        }

        // POST: NivelUmidades/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Faixa,DateAvaliacao")] NivelUmidade nivelUmidade)
        {
            if (id != nivelUmidade.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(nivelUmidade);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NivelUmidadeExists(nivelUmidade.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { message = "Registro atualizado com sucesso" });
            }
            return View(nivelUmidade);
        }

        // GET: NivelUmidades/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.NivelUmidade == null)
            {
                return NotFound();
            }

            var nivelUmidade = await _context.NivelUmidade
                .FirstOrDefaultAsync(m => m.Id == id);
            if (nivelUmidade == null)
            {
                return NotFound();
            }

            return View(nivelUmidade);
        }

        // POST: NivelUmidades/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.NivelUmidade == null)
            {
                return Problem("Entity set 'climei_mvcContext.NivelUmidade'  is null.");
            }
            var nivelUmidade = await _context.NivelUmidade.FindAsync(id);
            if (nivelUmidade != null)
            {
                _context.NivelUmidade.Remove(nivelUmidade);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { message = "Registro removido com sucesso" });
        }

        private bool NivelUmidadeExists(int id)
        {
          return (_context.NivelUmidade?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ClimeiMvc.Data;
using ClimeiMvc.Models;

namespace ClimeiMvc.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly climei_mvcContext _context;

        public UsuariosController(climei_mvcContext context)
        {
            _context = context;
        }

        // GET: Usuarios
        public async Task<IActionResult> Index(string searchString, string message)
        {
            ViewData["CurrentFilter"] = searchString;
            ViewBag.Message = message;

            var users = from u in _context.Usuario select u;
            if (!String.IsNullOrEmpty(searchString))
            {
                users = users.Where(u => u.Nome.Contains(searchString));
            }

            return View(await users.AsNoTracking().ToListAsync());
        }

        // GET: Usuarios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Usuario == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuario
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // GET: Usuarios/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Usuarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Email,Senha,Idade,Sexo")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                _context.Add(usuario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new {message = "Registro criado com sucesso" });
            }
            return View(usuario);
        }

        // GET: Usuarios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Usuario == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuario.FindAsync(id);
            if (usuario == null)
            {
                return NotFound();
            }
            return View(usuario);
        }

        // POST: Usuarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Email,Senha,Idade,Sexo")] Usuario usuario)
        {
            if (id != usuario.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(usuario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsuarioExists(usuario.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { message = "Registro atualizado com sucesso" });
            }
            return View(usuario);
        }

        // GET: Usuarios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Usuario == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuario
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // POST: Usuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Usuario == null)
            {
                return Problem("Entity set 'climei_mvcContext.Usuario'  is null.");
            }
            var usuario = await _context.Usuario.FindAsync(id);
            if (usuario != null)
            {
                _context.Usuario.Remove(usuario);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { message = "Registro deletado com sucesso" });
        }

        private bool UsuarioExists(int id)
        {
          return (_context.Usuario?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div>
    <h1 class="display-4 text-center">Climei – GLOBAL SOLUTION</h1>
    <h2 class="display-8">Dashboard</h2>

    <div class="d-flex gap-4">
        <a asp-controller="Usuarios" asp-action="Index" card-title="Usuários" card-icon="bi-people-fill" card-bg-color="bg-success" card-text='@ViewData["QntdUsers"]'>
            <!-- O conteúdo do Tag Helper será gerado aqui automaticamente -->
        </a>

        <a asp-controller="NivelUmidades" asp-action="Index" card-title="Níveis de Umidade" card-icon="bi-droplet-fill" card-bg-color="bg-primary" card-text='@ViewData["QntdUmidade"]'>
            <!-- O conteúdo do Tag Helper será gerado aqui automaticamente -->
        </a>

        <a asp-controller="NivelTemperaturas" asp-action="Index" card-title="Níveis de Temperatura" card-icon="bi-thermometer-half" card-bg-color="bg-danger" card-text='@ViewData["QntdTemp"]'>
            <!-- O conteúdo do Tag Helper será gerado aqui automaticamente -->
        </a>
    </div>

    <hr />
    <h2 class="display-8">Funcionalidades implementadas</h2>
    <p>Para essa solução ASP.NET Core foram implementadas o CRUD para as seguintes entidades:</p>
    <ul>
        <li><strong>Usuario e DadosUsuario</strong> - Entidades exclusivas para salvar informações do usuário. A primeira servindo para salvar dados gerais sobre o usuário e o segundo para todas as informações médicas necessárias. </li>
        <li><strong>LogAgua</strong> - Entidade feita para guardar o log de água ingerida por um usuário</li>
        <li><strong>LogTemperatura</strong> - Entidade feita para guardar o log de Temperatura, capturado pelo sensor de temperatura do usuário</li>
        <li><strong>LogUmidade</strong> - Entidade feita para guardar o log de Temperatura, capturado pelo sensor de umidade do usuário</li>
        <li><strong>LogBatimentoOxigenacao</strong> - Entidade feita para guardar o log de Temperatura, capturado pelo sensor de batimento cardíaco do usuário. Atualmente, devido a limitações técnicas do projeto, não foi possível utilizar o sensor de oxigenação para salvar os dados, logo iremos salvar apenas a frequência cardíaca.</li>
        <li><strong>NivelTemperatura</strong> - Entidade para guardar os diferentes níveis de "qualidade" da Temperatura (bom, ruim, excelente, etc)</li>
        <li><strong>NivelUmidade</strong> - Entidade para guardar os diferentes níveis de "qualidade" da Umidade (bom, ruim, excelente, etc)</li>
    </ul>
    <p>Tendo essa aplicação MVC em mãos, podemos usar ela como uma aplicação de suporte para o aplicativo da <strong>#Climei</strong>.</p>

    <hr />
    <h2 class="display-8">Funcionalidades além do CRUD</h2>
    <ul>
        <li>Dashboard na página Home</li>
        <li>Barra de pesquisa por nome na página de Usuários</li>
    </ul>
    <hr />
    <h2 class="display-8">Sobre a solução</h2>
    <p>O Climei é um aplicativo desenvolvido por nós da Technoware Solutions com o propósito de zelar pela saúde das pessoas em face das variáveis climáticas. Reconhecendo o impacto significativo do clima na saúde, o Climei oferece uma gama de funcionalidades para auxiliar os usuários a se protegerem dos efeitos adversos. Como por exemplo: em dias de calor intenso, onde a desidratação e o esgotamento por calor são preocupações, o aplicativo fornece orientações personalizadas, ou seja, recomendações como a ingestão de até 2 litros de água, permanecer em ambientes frescos, vestir roupas leves e evitar exercícios físicos intensos são adaptadas de acordo com as condições climáticas e as características individuais do usuário. Além disso, o Climei vai além, oferecendo alertas sobre a possibilidade de ondas de calor, conselhos específicos para quem lida com condições crônicas como diabetes ou asma, e sugestões de atividades físicas apropriadas para o clima do momento.</p>
    <p>A tecnologia por trás do Climei é impulsionada por sensores de Internet das Coisas (IoT), que monitoram em tempo real dados como temperatura, umidade, batimentos cardíacos e níveis de oxigenação no sangue. Essa coleta precisa de informações permite que o aplicativo forneça insights ainda mais refinados e personalizados. Por exemplo, ao utilizar os dados de temperatura e umidade, o Climei pode calcular a taxa de transpiração do usuário, fornecendo orientações específicas sobre a quantidade de água necessária para evitar a desidratação.</p>
    <p><strong>#Climatizado</strong></p>
</div>